name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract the current date
      id: vars
      run: echo "TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: kgseah/${{ github.repository }}:${{ env.TAG }}

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ env.TAG }}

    - name: Run Docker container
      run: |
        docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ env.TAG }}
